### ISSUE TITLE
Parser review

### ISSUE THREAD

**Issue by Inkvisto** [necobra/rust-habit-tracker-parser#1]
Для прохідного:
❌ ! Brief Description ( add more detailed description )
✔️ ! Project Name 
✔️ ! Grammar Rules
✔️ ! Unit Tests
✔️ ! Test Coverage
✔️ ! Core Files
❌ ! CLI ( implement help message & argument )

Для максимального:
✔️ Error Handling 
✔️ cargo fmt
✔️ cargo clippy
✔️ makefile
❌ Completeness 
✔️ Including a diagram or grammar in the Readme.md
✔️ Documentation
✔️ Publishing

❌ Курсова може бути зарахована
Бал: 13/20

**Comment by necobra** [comment]
Thank you for your review! I fixed the flaws.
